import fs from "fs";
import path from "path";
import { notesBase } from "./NotesBase.mjs";
import { readReleases } from "./releaseManifest.mjs";

const publicDir = path.join(process.cwd(), "public");
const outputFile = path.join(process.cwd(), "src", "data", "Notes.ts");

function formatDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}/${month}/${day}`;
}

function isExternalUrl(href = "") {
  return href.startsWith("http://") || href.startsWith("https://") || href.startsWith("mailto:");
}

function getLocalFilePath(href = "") {
  if (!href || isExternalUrl(href)) return null;

  const withoutHash = href.split("#")[0];
  const withoutQuery = withoutHash.split("?")[0];
  const decodedHref = decodeURIComponent(withoutQuery);
  const safeRelativePath = decodedHref.replace(/^\/+/, "");

  return path.join(publicDir, safeRelativePath);
}

function getFileDate(href) {
  const filePath = getLocalFilePath(href);

  if (!filePath) return "";

  if (!fs.existsSync(filePath)) {
    console.warn(`No local file found for date detection: ${href}`);
    return "";
  }

  const stats = fs.statSync(filePath);
  return formatDate(stats.mtime);
}

function getDateForResource(resource, latestRelease) {
  // A versioned note follows the latest version's recorded release date.
  // An unknown release date must not inherit a legacy date or a copied PDF's mtime.
  if (latestRelease) return latestRelease.date ?? "";

  // Prefer dateSourceHref. Otherwise use the main href. Otherwise use the first link.
  const candidateHref =
    resource.dateSourceHref ?? resource.href ?? resource.links?.[0]?.href ?? "";

  // If the local file exists, this is the detected modification date.
  // If the file is missing from public/document/, fall back to fallbackDate if provided.
  return getFileDate(candidateHref) || resource.fallbackDate || "";
}

const notesWithDates = notesBase.map((note) => {
  const { dateSourceHref, fallbackDate, description, releaseManifest, ...noteForWebsite } = note;
  const releases = releaseManifest !== undefined ? readReleases(publicDir, releaseManifest) : undefined;
  const latestRelease = releases?.[0];

  return {
    ...noteForWebsite,
    summary: note.summary ?? description ?? "",
    tags: note.tags ?? [],
    date: getDateForResource(note, latestRelease),
    ...(releases !== undefined ? { releases } : {}),
    ...(latestRelease ? { href: latestRelease.href } : {})
  };
});

const output = `// This file is automatically generated by scripts/generateNotes.mjs.
// Do not edit this file directly. Edit scripts/NotesBase.mjs instead.

export type NoteLink = {
  label: string;
  href: string;
};

export type NoteRelease = {
  version: string;
  date: string | null;
  href: string;
  summary: string;
  changes: string[];
};

export type Note = {
  slug: string;
  title: string;
  href?: string;
  summary: string;
  date: string;
  tags: string[];
  links?: NoteLink[];
  releases?: NoteRelease[];
};

export const notes: Note[] = ${JSON.stringify(notesWithDates, null, 2)};
`;

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, output, "utf8");
console.log(`Generated ${path.relative(process.cwd(), outputFile)}`);
