import fs from "fs";
import path from "path";
import { resourcesBase } from "./resourcesBase.mjs";

const publicDir = path.join(process.cwd(), "public");
const outputFile = path.join(process.cwd(), "src", "data", "resources.ts");

function formatDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}/${month}/${day}`;
}

function isExternalUrl(href = "") {
  return href.startsWith("http://") || href.startsWith("https://") || href.startsWith("mailto:");
}

function getLocalFilePath(href = "") {
  if (!href || isExternalUrl(href)) return null;

  const withoutHash = href.split("#")[0];
  const withoutQuery = withoutHash.split("?")[0];
  const decodedHref = decodeURIComponent(withoutQuery);
  const safeRelativePath = decodedHref.replace(/^\/+/, "");

  return path.join(publicDir, safeRelativePath);
}

function getFileDate(href) {
  const filePath = getLocalFilePath(href);

  if (!filePath) return "";

  if (!fs.existsSync(filePath)) {
    console.warn(`No local file found for date detection: ${href}`);
    return "";
  }

  const stats = fs.statSync(filePath);
  return formatDate(stats.mtime);
}

function getDateForResource(resource) {
  // Prefer dateSourceHref. Otherwise use the main href. Otherwise use the first link.
  const candidateHref =
    resource.dateSourceHref ?? resource.href ?? resource.links?.[0]?.href ?? "";

  // If the local file exists, this is the detected modification date.
  // If the file is missing from public/document/, fall back to fallbackDate if provided.
  return getFileDate(candidateHref) || resource.fallbackDate || "";
}

const resourcesWithDates = resourcesBase.map((resource) => {
  const { dateSourceHref, fallbackDate, ...resourceForWebsite } = resource;

  return {
    ...resourceForWebsite,
    date: getDateForResource(resource)
  };
});

const output = `// This file is automatically generated by scripts/generateResources.mjs.
// Do not edit this file directly. Edit scripts/resourcesBase.mjs instead.

export type ResourceLink = {
  label: string;
  href: string;
};

export type Resource = {
  title: string;
  href?: string;
  description?: string;
  date: string;
  links?: ResourceLink[];
};

export const resources: Resource[] = ${JSON.stringify(resourcesWithDates, null, 2)};
`;

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, output, "utf8");
console.log(`Generated ${path.relative(process.cwd(), outputFile)}`);
