import fs from "node:fs";
import path from "node:path";

function escapeHtml(value) {
  return value.replace(/[&<>"']/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
  })[character]);
}

// Use the already validated and sorted releases from the note generator.
// Only HTML is written; numbered PDFs remain untouched.
export function writeLatestPdfPages(publicDir, notes) {
  for (const note of notes) {
    if (note.releases === undefined) continue;
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(note.slug)) {
      throw new Error(`Cannot generate latest PDF page: invalid note slug "${note.slug}".`);
    }

    const latest = note.releases[0];
    const title = escapeHtml(note.title);
    // Resolve from notes/<slug>/latest/ under either / or /website/.
    const pdfHref = latest ? `../../../${latest.href}` : undefined;
    const historyHref = `../../../#/notes/${note.slug}`;
    const redirect = pdfHref ? `
    <meta http-equiv="refresh" content="0;url=${escapeHtml(pdfHref)}">
    <script>window.location.replace(${JSON.stringify(pdfHref).replace(/</g, "\\u003c")});</script>` : "";
    const body = latest ? `
    <h1>Opening ${title}</h1>
    <p>You are being redirected to version ${escapeHtml(latest.version)}.</p>
    <p>If the PDF does not open automatically, <a href="${escapeHtml(pdfHref)}">Open PDF</a>.</p>` : `
    <h1>${title}</h1>
    <p>No PDF is available yet.</p>`;
    const output = `<!doctype html>
<!-- Generated by scripts/generateNotes.mjs. Do not edit directly. -->
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark">
    <title>${title} — latest PDF</title>${redirect}
    <style>
      :root { color-scheme: light dark; font-family: system-ui, sans-serif; }
      body { max-width: 40rem; margin: 3rem auto; padding: 0 1.5rem; line-height: 1.6; }
      h1 { line-height: 1.2; }
      a { color: LinkText; }
      a:focus-visible { outline: 2px solid currentColor; outline-offset: 4px; }
    </style>
  </head>
  <body>${body}
    <p><a href="${historyHref}">View release history</a></p>
  </body>
</html>
`;
    const outputFile = path.join(publicDir, "notes", note.slug, "latest", "index.html");
    fs.mkdirSync(path.dirname(outputFile), { recursive: true });
    fs.writeFileSync(outputFile, output, "utf8");
    console.log(`Generated ${path.relative(process.cwd(), outputFile)}`);
  }
}
