// This file is automatically generated by scripts/generateNotes.mjs.
// Do not edit this file directly. Edit scripts/NotesBase.mjs instead.

export type NoteLink = {
  label: string;
  href: string;
};

export type NoteRelease = {
  version: string;
  date: string | null;
  href: string;
  summary: string;
  changes: string[];
};

export type Note = {
  slug: string;
  title: string;
  href?: string;
  summary: string;
  date: string;
  tags: string[];
  links?: NoteLink[];
  releases?: NoteRelease[];
};

export const notes: Note[] = [
  {
    "slug": "fluid-mechanics",
    "title": "Fluid Mechanics",
    "summary": "About some interesting parts of fluid mechanics I thought of.",
    "tags": [
      "Fluid dynamics",
      "Personal notes"
    ],
    "date": "2026/07/23",
    "releases": [
      {
        "version": "0.4",
        "date": "2026/07/23",
        "href": "document/fluid_mechanics/Fluid_Mechanics_v0.4.pdf",
        "summary": "",
        "changes": [
          "Modify stress-tensor, energy-conservation and add citation."
        ]
      },
      {
        "version": "0.3",
        "date": "2026/06/23",
        "href": "document/fluid_mechanics/Fluid_Mechanics_v0.3.pdf",
        "summary": "",
        "changes": [
          "Add exercises."
        ]
      },
      {
        "version": "0.2",
        "date": "2026/06/21",
        "href": "document/fluid_mechanics/Fluid_Mechanics_v0.2.pdf",
        "summary": "",
        "changes": [
          "Refine Content: conservation laws, Navier-Stokes equation, naming of equation.",
          "Add references."
        ]
      },
      {
        "version": "0.1",
        "date": "2023/10/06",
        "href": "document/fluid_mechanics/Fluid_Mechanics_v0.1.pdf",
        "summary": "Baby version by Word.",
        "changes": []
      }
    ],
    "href": "document/fluid_mechanics/Fluid_Mechanics_v0.4.pdf"
  },
  {
    "slug": "olympiad-record",
    "title": "Olympiad Record",
    "summary": "My own experience during preparation.",
    "tags": [
      "Personal notes"
    ],
    "href": "document/Olympiad_Record.pdf",
    "links": [
      {
        "label": "Main file",
        "href": "document/Olympiad_Record.pdf"
      }
    ],
    "date": "2026/09/12"
  },
  {
    "slug": "jackson-electrodynamics",
    "title": "Notes on Classical Electrodynamics 3rd edition, John David Jackson",
    "summary": "Handouts and study notes for the third edition of Jackson's Classical Electrodynamics.",
    "tags": [
      "Electrodynamics",
      "Handouts"
    ],
    "href": "document/Jackson_Handouts.pdf",
    "links": [
      {
        "label": "Main file",
        "href": "document/Jackson_Handouts.pdf"
      }
    ],
    "date": "2024/06/05"
  },
  {
    "slug": "differential-geometry-general-relativity",
    "title": "Differential Geometry and General Relativity",
    "summary": "A work in progress on the geometric language of general relativity.",
    "tags": [
      "Differential geometry",
      "General relativity",
      "Work in progress"
    ],
    "href": "https://github.com/WilliamWang941225/Differential-Geometry-and-General-Relativity/raw/main/Differential%20Geometry%20and%20General%20Relativity.pdf",
    "links": [
      {
        "label": "GitHub PDF",
        "href": "https://github.com/WilliamWang941225/Differential-Geometry-and-General-Relativity/raw/main/Differential%20Geometry%20and%20General%20Relativity.pdf"
      }
    ],
    "date": ""
  },
  {
    "title": "7th Tian Wu Physics Competition Final (第七屆天物盃決賽) - Q3",
    "slug": "tian-wu-physics-q3",
    "summary": "The problem, solution, and original announcement for Question 3 of the final round.",
    "tags": [
      "Physics competition",
      "Problem solution"
    ],
    "links": [
      {
        "label": "Problem",
        "href": "document/Tian-Wu_Physics_Cup_Q3.pdf"
      },
      {
        "label": "Solution",
        "href": "document/Tian-Wu_Physics_Cup_A3.pdf"
      },
      {
        "label": "Original Facebook link",
        "href": "https://www.facebook.com/share/p/AW9EGxkNH9CqTBhx/"
      }
    ],
    "date": "2024/06/18"
  },
  {
    "title": "2024 IPhOC 秒題大賽 - Q2",
    "slug": "iphoc-2024-q2",
    "summary": "Question 2, its answer, and the official solution and marking scheme from IPhOC 2024.",
    "tags": [
      "Physics competition",
      "Problem solution"
    ],
    "links": [
      {
        "label": "Problem",
        "href": "document/Q2.pdf"
      },
      {
        "label": "Answer",
        "href": "document/S2.pdf"
      },
      {
        "label": "Solution and Marking Scheme",
        "href": "document/S2_full.pdf"
      }
    ],
    "date": "2024/07/17"
  },
  {
    "slug": "gravity",
    "title": "Gravity",
    "summary": "Lecture materials prepared for the CCHS Physics Book Club, with handouts as the primary reference.",
    "tags": [
      "General relativity",
      "Lecture materials"
    ],
    "links": [
      {
        "label": "Lecture Handouts",
        "href": "document/Gravity_Handouts.pdf"
      },
      {
        "label": "Lecture Notes",
        "href": "document/Gravity_Leture_Notes.pdf"
      }
    ],
    "date": "2024/06/13"
  },
  {
    "slug": "physics-cup-2024-problem-4",
    "title": "Solution to Problem 4 of Physics Cup 2024",
    "summary": "A worked solution to the fourth problem from Physics Cup 2024.",
    "tags": [
      "Physics competition",
      "Problem solution"
    ],
    "href": "document/Physics_Cup_2024.pdf",
    "links": [
      {
        "label": "Solution",
        "href": "document/Physics_Cup_2024.pdf"
      },
      {
        "label": "Problem statement",
        "href": "https://physicscup.ee/physics-cup-taltech-2024-problem-4/"
      }
    ],
    "date": "2024/10/16"
  }
];
