// This file is automatically generated by scripts/generateNotes.mjs.
// Do not edit this file directly. Edit scripts/NotesBase.mjs instead.

export type NoteLink = {
  label: string;
  href: string;
};

export type Note = {
  title: string;
  href?: string;
  description?: string;
  date: string;
  links?: NoteLink[];
};

export const notes: Note[] = [
  {
    "title": "Fluid Mechanics",
    "description": "About some interesting parts of fluid mechanics I thought of.",
    "href": "document/Fluid Mechanics.pdf",
    "links": [
      {
        "label": "Main file",
        "href": "document/Fluid Mechanics.pdf"
      },
      {
        "label": "Old version",
        "href": "document/Fluid Mechanics (old ver).pdf"
      }
    ],
    "date": "2026/07/23"
  },
  {
    "title": "Notes on Classical Electrodynamics 3rd edition, John David Jackson",
    "href": "document/Jackson_Handouts.pdf",
    "links": [
      {
        "label": "Main file",
        "href": "document/Jackson_Handouts.pdf"
      }
    ],
    "date": "2024/06/05"
  },
  {
    "title": "Differential Geometry and General Relativity",
    "description": "Still progressing.",
    "href": "https://github.com/WilliamWang941225/Differential-Geometry-and-General-Relativity/raw/main/Differential%20Geometry%20and%20General%20Relativity.pdf",
    "links": [
      {
        "label": "GitHub PDF",
        "href": "https://github.com/WilliamWang941225/Differential-Geometry-and-General-Relativity/raw/main/Differential%20Geometry%20and%20General%20Relativity.pdf"
      }
    ],
    "date": ""
  },
  {
    "title": "7th Tian Wu Physics Competition Final (第七屆天物盃決賽) - Q3",
    "links": [
      {
        "label": "Problem",
        "href": "document/Tian-Wu_Physics_Cup_Q3.pdf"
      },
      {
        "label": "Solution",
        "href": "document/Tian-Wu_Physics_Cup_A3.pdf"
      },
      {
        "label": "Original Facebook link",
        "href": "https://www.facebook.com/share/p/AW9EGxkNH9CqTBhx/"
      }
    ],
    "date": "2024/06/18"
  },
  {
    "title": "2024 IPhOC 秒題大賽 - Q2",
    "links": [
      {
        "label": "Problem",
        "href": "document/Q2.pdf"
      },
      {
        "label": "Answer",
        "href": "document/S2.pdf"
      },
      {
        "label": "Solution and Marking Scheme",
        "href": "document/S2_full.pdf"
      }
    ],
    "date": "2024/07/17"
  },
  {
    "title": "Gravity",
    "description": "Lecture materials prepared for the CCHS Physics Book Club. Please be aware that there could be mistakes in the lecture notes as they were compiled earlier. If there are any differences between the two, please refer to the handouts as the primary source.",
    "links": [
      {
        "label": "Lecture Handouts",
        "href": "document/Gravity Handouts.pdf"
      },
      {
        "label": "Lecture Notes",
        "href": "document/Gravity Leture Notes.pdf"
      }
    ],
    "date": "2024/06/13"
  },
  {
    "title": "Solution to Problem 4 of Physics Cup 2024",
    "href": "document/Physics_Cup_2024.pdf",
    "links": [
      {
        "label": "Solution",
        "href": "document/Physics_Cup_2024.pdf"
      },
      {
        "label": "Problem statement",
        "href": "https://physicscup.ee/physics-cup-taltech-2024-problem-4/"
      }
    ],
    "date": "2024/10/16"
  }
];
